CREATE SEQUENCE SQ_USERS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TB_USERS (
    ID_USER INTEGER DEFAULT SQ_USERS.NEXTVAL NOT NULL,
    NM_NAME VARCHAR2(100) NOT NULL,
    DS_EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    DS_PASSWORD VARCHAR2(20) NOT NULL,
    ROLE VARCHAR2(50) DEFAULT 'USER'
)